import {
    QueryClientProvider,
    useQueryClient
} from "@tanstack/react-query";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const query = useQueryClient();
  return (
    <html lang="en">
      <body className="bg-black">
        <QueryClientProvider client={query}>{children}</QueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
